# -*- coding: utf-8 -*-
"""column.2c.weka classification Using KNeighborsClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XAkEXAwmG8j01988T3si3_BDOvrToCDQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/column_2C_weka.csv')

df.head(10)

df.tail(10)

df.shape

df.info(20)

df.describe()

a=df['degree_spondylolisthesis']
plt.plot(a)

b=['class']
c=['pelvic_incidence']
plt.scatter(b,c)

d=df['class']
plt.hist(c)

e=df['sacral_slope']
plt.bar(e,width=100,height=100)

h=df['lumbar_lordosis_angle']
plt.pie(h)

l=df['pelvic_incidence']
k=df['lumbar_lordosis_angle']
sns.lineplot(x=l,y=k,data=df)

o=df['lumbar_lordosis_angle']
p=df['sacral_slope']
sns.scatterplot(x=o,y=p,data=df)

u=df['lumbar_lordosis_angle']
i=df['pelvic_radius']
sns.barplot(x=u,y=i,data=df)

sns.countplot(x='pelvic_incidence',data=df)

sns.pairplot(df,hue='pelvic_incidence')

x=[25,34,56,5,80,25,100,40]
y=[10,20,30,40,50,60,70,80]
sns.distplot(x,y)

df.isnull().sum()

v=df['sacral_slope']
sns.boxplot(v)

l=df.drop('class',axis=1)
l

m=df['class']
m

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(l,m,test_size=0.20,random_state=0)

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

x=StandardScaler()

A=x.fit_transform(x_train)

A

from sklearn.neighbors import KNeighborsClassifier

clf=KNeighborsClassifier(knn=3)

clf.fit(x_train,y_train)

pred=clf.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(pred,y_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(pred,y_test)