# -*- coding: utf-8 -*-
"""Gender_classification using KNeighborsClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VB6pMIp9tOjPUpoMc-VUlLZnrdYaSUn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/gender_classification_v7.csv')

df.head(10)

df.tail(10)

df.shape

df.info(10)

df.describe()

a=df['long_hair']
plt.plot(a)

b=df['nose_wide']
c=df['nose_long']
plt.scatter(b,c)

d=df['nose_long']
plt.hist(d)

e=df['forehead_width_cm']
plt.bar(e,width=100,height=100)

t=df['nose_wide']
plt.pie(t)

a=df['distance_nose_to_lip_long']
b=df['gender']
sns.lineplot(x=a,y=b,data=df)

e=df['lips_thin']
l=df['gender']
sns.scatterplot(x=e,y=l,data=df)

j=df['lips_thin']
h=df['nose_long']
sns.barplot(x=j,y=h,data=df)

sns.countplot(x='lips_thin',data=df)

sns.pairplot(df,hue='lips_thin')

d=[12,54,56]
f=[10,20,30]
sns.distplot(d,f)

df.isnull().sum()

x=df['lips_thin']
sns.boxplot(x)

from sklearn.preprocessing import LabelEncoder

a=LabelEncoder()

g=df['gender']
g

df['gender']=a.fit_transform(g)

x=df.drop('gender',axis=1)
x

y=df['gender']
y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

S=StandardScaler()

v=S.fit_transform(x_train)

v

from sklearn.neighbors import KNeighborsClassifier

Classifier=KNeighborsClassifier(n_neighbors=8)

Classifier.fit(x_train,y_train)

pred=Classifier.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(pred,y_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(pred,y_test)